version: "3"

services:

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - 3306:3306