version: "3"

services:

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ../todo-app-api/:/var/www/
    working_dir: /var/www/
  
  php:
    build: ./php/
    user: $user
    container_name: php
    volumes:
      - ../todo-app-api/:/var/www/
  
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf

  react:
    image: node:14.17.0
    container_name: react
    volumes:
      - ../todo-app-web:/mnt/app/
    working_dir: /mnt/app/
    command: sh -c "npm install && npm run start"
    ports:
      - "3000:3000"